version: '3'

services:
  nginx:
     image: nginx-dswa:latest
     build: ./nginx/
     container_name: dswa-nginx
     ports:
       - "8888:80"
     volumes:
       - ./app:/var/www/dswa
       - ./nginx/vhost/vhost.conf:/etc/nginx/conf.d/default.conf
       - ./nginx/logs:/var/log/nginx
     links:
       - php
     networks:
       - dswa-net
  php:
     image: php-fpm-dswa
     build: ./php-fpm/
     container_name: dswa-php
     ports:
       - "9000:9000"
     volumes:
       - ./app:/var/www/dswa
     networks:
       - dswa-net

networks:
  dswa-net:
